// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/container/gmap"
)

// CheckinDetail is the golang structure for table checkin_detail.
type CheckinDetail internal.CheckinDetail

// Fill with you ideas below.

// ws消息
type CheckInMsg struct {
	Type int
	Data gmap.StrStrMap
}

type StartCheckInReq struct {
	SecretKey string
	CourseId  int
	Duration  int
	Name      string
}

type CheckinDetailResp struct {
	StuId           int    `json:"stu_id"`            // 学生id
	Num             int    `json:"num"`               // 学号
	RealName        int    `json:"real_name"`         // 真名
	Organization    string `json:"organization"`      // 单位
	CourseId        int    `json:"course_id"`         // 课程id
	CheckinRecordId int    `json:"checkin_record_id"` // 签到id
	IsCheckIn       bool   `json:"is_check_in"`       // 是否签到
}

type CheckinDetailPageResp struct {
	Records  []*CheckinDetailResp `json:"records"`
	PageInfo *response.PageInfo   `json:"page_info"`
}
