// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/os/gtime"
)

// CheckinRecord is the golang structure for table checkin_record.
type CheckinRecord internal.CheckinRecord

// Fill with you ideas below.

type CheckinRecordResp struct {
	CheckinRecordId int         `json:"checkin_record_id"` // id
	Name            string      `json:"name"`              // 签到名称，例如2021年2月5日签到
	CourseId        int         `json:"course_id"`         // 课程id
	Actual          int         `json:"actual"`            // 实际人数
	Total           int         `json:"total"`             // 选课人数
	CreatedAt       *gtime.Time `json:"created_at"`        // 创建时间
	UpdatedAt       *gtime.Time `json:"updated_at"`        // 更新时间
}

type CheckinRecordPageResp struct {
	Records  []*CheckinRecordResp `json:"records"`
	PageInfo *response.PageInfo   `json:"page_info"`
}

type ListCheckinRecordsReq struct {
	CourseId    int // 课程id
	PageCurrent int // 页码
	PageSize    int // 页面大小
}

type ListCheckinDetailsReq struct {
	CheckInRecordId int // 课程id
	PageCurrent     int // 页码
	PageSize        int // 页面大小
}

type UpdateCheckinDetail struct {
	StuId           int
	CheckinRecordId int
	IsCheckIn       bool
}
