// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
)

// CourseComment is the golang structure for table course_comment.
type CourseComment internal.CourseComment

// Fill with you ideas below.

type CourseCommentEntity struct {
	Comment       *CourseComment   `json:"comment"`       // 评论主体
	ReplyComments []*CourseComment `json:"replyComments"` // 子评论
}

// CourseCommentEntityResp 返回集
type CourseCommentEntityResp struct {
	Records  []*CourseCommentEntity `json:"records"`
	PageInfo *response.PageInfo     `json:"pageInfo"` // 页面信息
}
