// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/os/gtime"
)

// CourseRecourse is the golang structure for table course_recourse.
type CourseRecourse internal.CourseRecourse

// Fill with you ideas below.

type CourseRecourseResp struct {
	CourseRecourseId int         `orm:"course_recourse_id,primary" json:"course_recourse_id"` // id
	Title            string      `orm:"title"                      json:"title"`              // 标题，限20字
	Content          string      `orm:"content"                    json:"content"`            // 公告内容，无字数限制
	AttachmentUrl    *string     `orm:"attachment_url"             json:"attachment_url"`     // 附件url
	CreatedAt        *gtime.Time `orm:"created_at"                 json:"created_at"`         // 创建时间
	UpdatedAt        *gtime.Time `orm:"updated_at"                 json:"updated_at"`         // 修改时间
}

type InsertCourseRecourseReq struct {
	CourseId      int     // 课程id
	Title         string  // 标题，限20字
	Content       string  // 公告内容，无字数限制
	AttachmentUrl *string // 附件url
}

type UpdateCourseRecourseReq struct {
	CourseRecourseId int     // 课程id
	Title            string  // 标题，限20字
	Content          string  // 公告内容，无字数限制
	AttachmentUrl    *string // 附件url
}

type ListCourseResourceReq struct {
	CourseId int
	response.PageReq
}
