// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
)

// Course is the golang structure for table course.
type Course internal.Course

// Fill with you ideas below.

type CoursePageResp struct {
	Records  []*Course
	PageInfo *response.PageInfo
}

//type NewCourseReq struct {
//	TeacherId  int    // 教师id
//	CourseDes  string // 课程描述,限200字
//	CourseName string // 课程名称，限长15字
//	SecretKey  string // 加入课程的密码
//}

// 课程修改
//type CourseModifyReq struct {
//	CourseId   int    // 主键
//	TeacherId  int    // 教师id
//	CourseName string // 课程名称，限长15字
//	CourseDes  string // 课程描述,限两百字
//	SecretKey  string // 加入课程的密码
//	Deleted    int    // 删除标志
//	Closed     int    // 结课标志
//}

// 加入课程
type JoinCourseReq struct {
	UserId    int // 学生id
	CourseId  int // 课程id
	SecretKey int // 加入课程的密码
}
