// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
)

// Lab is the golang structure for table lab.
type Lab internal.Lab

// Fill with you ideas below.
