// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/os/gtime"
)

// Lab is the golang structure for table lab.
type Lab internal.Lab

// Fill with you ideas below.

type LabResp struct {
	LabId         int         `orm:"lab_id,primary" json:"lab_id"`         // 主键
	CourseId      int         `orm:"course_id"      json:"course_id"`      // 该实验隶属的课程
	Title         string      `orm:"title"          json:"title"`          // 标题
	Description   string      `orm:"description"    json:"description"`    // 实验内容描述，无字数限制
	AttachmentUrl *string     `orm:"attachment_url" json:"attachment_url"` // 实验附件url
	DeadLine      *gtime.Time `orm:"dead_line"      json:"dead_line"`      // 截止时间
	CreatedAt     *gtime.Time `orm:"created_at"     json:"created_at"`     // 创建时间
	UpdatedAt     *gtime.Time `orm:"updated_at"     json:"updated_at"`     // 修改时间
}

type UpdateLabReq struct {
	LabId         int         `orm:"lab_id,primary" json:"lab_id"`         // 主键
	Title         *string     `orm:"title"          json:"title"`          // 标题
	Description   *string     `orm:"description"    json:"description"`    // 实验内容描述，无字数限制
	AttachmentUrl *string     `orm:"attachment_url" json:"attachment_url"` // 实验附件url
	DeadLine      *gtime.Time `orm:"dead_line"      json:"dead_line"`      // 截止时间
}

type InsertLabReq struct {
	CourseId      int         // 该实验隶属的课程
	Title         string      // 标题
	Description   string      // 实验内容简介
	AttachmentUrl *string     // 实验附件url
	DeadLine      *gtime.Time // 截止时间
}

type ListLabReq struct {
	response.PageReq
	CourseId int
}

type CodingTime struct {
	CodingTimeId int
	Duration     int
	CreatedAt    *gtime.Time
	UpdatedAt    *gtime.Time
}
