// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
)

// LabComment is the golang structure for table lab_comment.
type LabComment internal.LabComment

// Fill with you ideas below.

type LabCommentEntity struct {
	Comment       *LabComment   // 评论主体
	ReplyComments []*LabComment // 子评论
}

// CourseCommentEntityResp 返回集
type LabCommentEntityResp struct {
	Records  []*LabCommentEntity
	PageInfo *response.PageInfo // 页面信息
}
