// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/os/gtime"
)

// LabSubmit is the golang structure for table lab_submit.
type LabSubmit internal.LabSubmit

// Fill with you ideas below.

type LabSummitResp struct {
	LabSubmitId int         `orm:"lab_submit_id,primary" json:"lab_submit_id"`  //
	UserId      int         `orm:"user_id"                json:"stu_id"`        // 用户id
	RealName    string      `orm:"real_name"              json:"stu_real_name"` //
	Num         string      `orm:"num"                    json:"stu_num"`       // 学号
	ReportUrl   string      `orm:"report_url"             json:"report_url"`    // 存放实验报告pdf的url
	FinishStat  int         `orm:"finish_stat"            json:"finish_stat"`   // 是否完成代码
	CodingTime  int         `json:"coding_time"`                                // 编码时间
	CreatedTime *gtime.Time `orm:"created_time"           json:"created_time"`  // 创建时间
	UpdatedTime *gtime.Time `orm:"updated_time"           json:"updated_time"`  // 更新时间
}

type SummitReportReq struct {
	ReportUrl string
	LabId     int
	StuId     int
}

type SummitLabFinishReq struct {
	IsFinish bool // 是否已经完成
	LabId    int
	StuId    int
}

type SelectLabSummitReq struct {
	response.PageReq
	LabId int
}

type SelectCodingTimeReq struct {
	response.PageReq
	LabId int
}

type SelectCompilerErrorLogReq struct {
	response.PageReq
	LabId int
}
