// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
	"github.com/gogf/gf/os/gtime"
)

// Message is the golang structure for table message.
type Message internal.Message

// Fill with you ideas below.

type ListMessageReq struct {
	UserId int
	response.PageReq
}

type ListMessageResp struct {
	MessageId  int         `orm:"message_id,primary" json:"message_id"`  // id
	ReceiverId int         `orm:"receiver_id"        json:"receiver_id"` // 接收者id
	Type       int         `orm:"type"               json:"type"`        // 消息类型
	Content    string      `orm:"content"            json:"content"`     // 消息内容
	MessageDes string      `orm:"message_des"        json:"message_des"` // 消息描述
	ContentId  int         `orm:"content_id"         json:"content_id"`  // 消息来源id
	IsRead     int         `orm:"is_read"            json:"is_read"`     // 是否已读
	CreatedAt  *gtime.Time `orm:"created_at"         json:"created_at"`  // 创建时间
	UpdatedAt  *gtime.Time `orm:"updated_at"         json:"updated_at"`  // 更新时间
	DeletedAt  *gtime.Time `orm:"deleted_at"         json:"deleted_at"`  // 删除时间
}
