// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
)

// SignInCourse is the golang structure for table signIn_course.
type SignInCourse internal.SignInCourse

// Fill with you ideas below.
