// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
)

// SysApiRole is the golang structure for table sys_api_role.
type SysApiRole internal.SysApiRole

// Fill with you ideas below.