// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
)

// SysApi is the golang structure for table sys_api.
type SysApi internal.SysApi

// Fill with you ideas below.