// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
	"code-platform/library/common/response"
)

// SysUser is the golang structure for table sys_user.
type SysUser internal.SysUser

// Fill with you ideas below.

type SysUserPageResp struct {
	Records  []*SysUser
	PageInfo *response.PageInfo
}

// 注册请求注册参数
type SignUpReq struct {
	Email            string // 邮箱
	NickName         string // 昵称
	RealName         string // 真实姓名
	AvatarUrl        string // 头像url
	Num              string // 学号
	Gender           int    // 性别
	Password         string // 密码
	Major            string // 专业
	Organization     string // 单位
	VerificationCode string // 验证码
}

// 登录请求参数
type LoginReq struct {
	Username string // 用户名
	Password string // 密码
}

// 修改请求参数
type UserUpdateReq struct {
	UserId       int    // 主键
	NickName     string // 昵称
	RealName     string // 真实姓名
	Num          string // 学号
	AvatarUrl    string // 头像url
	OldPassword  string // 旧密码
	Password     string // 新密码
	Gender       int    // 性别
	Major        string // 专业
	Organization string // 单位
}

// 重置密码请求注册参数
type ResetPasswordReq struct {
	Email            string // 邮箱
	Password         string // 密码
	VerificationCode string // 验证码
}

// 注销用户请求参数
type DeletedUserReq struct {
	UserId           int    // 主键
	Password         string // 密码
	VerificationCode string // 验证码
}
