// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"code-platform/app/model/internal"
)

// SysUser is the golang structure for table sys_user.
type SysUser internal.SysUser

// Fill with you ideas below.

// 请求注册参数
type SysUserRegisterReq struct {
	Email        string // 邮箱
	NickName     string // 昵称
	RealName     string // 真实姓名
	Num          string // 学号
	Password     string // 密码
	Major        string // 专业
	Organization string // 单位
}

// 登录请求参数，用于前后端交互参数格式约定
type SysUserSignInReq struct {
	Passport string
	Password string
}

// 昵称唯一性检测请求参数，用于前后端交互参数格式约定
type SysUserCheckNickNameReq struct {
	Nickname string
}

// 邮箱唯一性检测请求参数，用于前后端交互参数格式约定
type SysUserCheckEmailReq struct {
	Email string
}

// 登录请求参数，用于前后端交互参数格式约定
type LoginReq struct {
	Username string
	Password string
}

// 登录请求参数，用于前后端交互参数格式约定
type UserModifyReq struct {
	NickName     string // 昵称
	RealName     string // 真实姓名
	Num          string // 学号
	OldPassword  string // 旧密码
	NewPassword  string `orm:"password"` // 新密码
	Gender       int    // 性别
	Major        string // 专业
	Organization string // 单位
}
