// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CheckinDetail is the golang structure for table checkin_detail.
type CheckinDetail struct {
	CheckinDetailId int         `orm:"checkin_detail_id,primary" json:"checkin_detail_id"` // id
	StuId           int         `orm:"stu_id"                    json:"stu_id"`            // 学生id
	CheckinRecordId int         `orm:"checkin_record_id"         json:"checkin_record_id"` // 签到记录id
	CreatedAt       *gtime.Time `orm:"created_at"                json:"created_at"`        // 创建时间
	UpdatedAt       *gtime.Time `orm:"updated_at"                json:"updated_at"`        // 更新时间
	DeletedAt       *gtime.Time `orm:"deleted_at"                json:"deleted_at"`        // 删除时间
}
