// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CheckinRecord is the golang structure for table checkin_record.
type CheckinRecord struct {
	CheckinRecordId int         `orm:"checkin_record_id,primary" json:"checkin_record_id"` // id
	Name            string      `orm:"name"                      json:"name"`              // 签到名称，例如2021年2月5日签到
	CourseId        int         `orm:"course_id"                 json:"course_id"`         // 课程id
	CreatedAt       *gtime.Time `orm:"created_at"                json:"created_at"`        // 创建时间
	UpdatedAt       *gtime.Time `orm:"updated_at"                json:"updated_at"`        // 更新时间
	DeletedAt       *gtime.Time `orm:"deleted_at"                json:"deleted_at"`        // 删除时间
}
