// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CourseComment is the golang structure for table course_comment.
type CourseComment struct {
	CourseCommentId int         `orm:"course_comment_id,primary" json:"courseCommentId"` // 主键
	CourseId        int         `orm:"course_id"                 json:"courseId"`        // 实验内容
	CommentText     string      `orm:"comment_text"              json:"commentText"`     // 评论内容
	Pid             int         `orm:"pid"                       json:"pid"`             // 父评论id，主评时为空
	UserId          int         `orm:"user_id"                   json:"userId"`          // 发评论的用户id
	Username        string      `orm:"username"                  json:"username"`        // 回复者的用户名
	ReplyUsername   string      `orm:"reply_username"            json:"replyUsername"`   // 被回复者的用户名
	ReplyId         int         `orm:"reply_id"                  json:"replyId"`         // 回复的评论id
	CreatedAt       *gtime.Time `orm:"created_at"                json:"createdAt"`       // 创建时间
	UpdatedAt       *gtime.Time `orm:"updated_at"                json:"updatedAt"`       // 更新时间
	DeletedAt       *gtime.Time `orm:"deleted_at"                json:"deletedAt"`       // 删除时间
}
