// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Course is the golang structure for table course.
type Course struct {
	CourseId   int         `orm:"course_id,primary" json:"courseId"`   // 主键
	TeacherId  int         `orm:"teacher_id"        json:"teacherId"`  // 教师id
	CourseName string      `orm:"course_name"       json:"courseName"` // 课程名称，限长15字
	CourseDes  string      `orm:"course_des"        json:"courseDes"`  // 课程描述,限两百字
	SecretKey  int         `orm:"secret_key"        json:"secretKey"`  // 加入课程的密码,6位
	Closed     int         `orm:"closed"            json:"closed"`     // 结课标志
	CreatedAt  *gtime.Time `orm:"created_at"        json:"createdAt"`  // 创建时间
	UpdatedAt  *gtime.Time `orm:"updated_at"        json:"updatedAt"`  // 修改时间
	DeletedAt  *gtime.Time `orm:"deleted_at"        json:"deletedAt"`  // 删除时间
}
