// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CourseRecourse is the golang structure for table course_recourse.
type CourseRecourse struct {
	CourseRecourseId int         `orm:"course_recourse_id,primary" json:"course_recourse_id"` //
	CourseId         int         `orm:"course_id"                  json:"course_id"`          // 课程id
	Title            string      `orm:"title"                      json:"title"`              // 标题，限20字
	Content          string      `orm:"content"                    json:"content"`            // 公告内容，无字数限制
	AttachmentUrl    string      `orm:"attachment_url"             json:"attachment_url"`     // 附件url
	CreatedAt        *gtime.Time `orm:"created_at"                 json:"created_at"`         // 创建时间
	UpdatedAt        *gtime.Time `orm:"updated_at"                 json:"updated_at"`         // 修改时间
	DeletedAt        *gtime.Time `orm:"deleted_at"                 json:"deleted_at"`         // 删除时间
}
