// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CourseComment is the golang structure for table course_comment.
type CourseComment struct {
	CourseCommentId int         `orm:"course_comment_id,primary" json:"course_comment_id"` // 主键
	CourseId        int         `orm:"course_id"                 json:"course_id"`         // 实验内容
	CommentText     string      `orm:"comment_text"              json:"comment_text"`      // 评论内容，限120字
	Pid             int         `orm:"pid"                       json:"pid"`               // 父评论id，主评时为空
	UserId          int         `orm:"user_id"                   json:"user_id"`           // 发评论的用户id
	ReplyUserId     int         `orm:"reply_user_id"             json:"reply_user_id"`     // 回复的userId
	CreatedAt       *gtime.Time `orm:"created_at"                json:"created_at"`        // 创建时间
	UpdatedAt       *gtime.Time `orm:"updated_at"                json:"updated_at"`        // 更新时间
	DeletedAt       *gtime.Time `orm:"deleted_at"                json:"deleted_at"`        // 删除时间
}
