// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// LabSubmit is the golang structure for table lab_submit.
type LabSubmit struct {
	LabSubmitId int `orm:"lab_submit_id,primary" json:"labSubmitId"` //
	LabId       int `orm:"lab_id"                json:"labId"`       //
}
