// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// LabComment is the golang structure for table lab_comment.
type LabComment struct {
	LabCommentId  int         `orm:"lab_comment_id,primary" json:"labCommentId"`  // 主键
	LabId         int         `orm:"lab_id"                 json:"labId"`         // 实验id
	CommentText   string      `orm:"comment_text"           json:"commentText"`   // 评论内容
	Pid           int         `orm:"pid"                    json:"pid"`           // 父评论id，主评时为0
	UserId        int         `orm:"user_id"                json:"userId"`        // 发评论的用户id
	Username      string      `orm:"username"               json:"username"`      // 被回复的用户名称
	ReplyId       int         `orm:"reply_id"               json:"replyId"`       // 被回复的用户id
	ReplyUsername string      `orm:"reply_username"         json:"replyUsername"` // 被回复的用户名称
	CreatedAt     *gtime.Time `orm:"created_at"             json:"createdAt"`     // 创建时间
	UpdatedAt     int         `orm:"updated_at"             json:"updatedAt"`     // 更新时间
	DeletedAt     *gtime.Time `orm:"deleted_at"             json:"deletedAt"`     // 删除时间
}
