// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// LabSubmit is the golang structure for table lab_submit.
type LabSubmit struct {
	LabSubmitId   int    `orm:"lab_submit_id,primary" json:"labSubmitId"`   //
	LabId         int    `orm:"lab_id"                json:"labId"`         // lab id
	ReportUrl     string `orm:"report_url"            json:"reportUrl"`     // 存放实验报告pdf的url
	TempReportUrl string `orm:"temp_report_url"       json:"tempReportUrl"` // 暂存实验报告url
	IsCode        int    `orm:"is_code"               json:"isCode"`        // 代码是否提交
}
