// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Message is the golang structure for table message.
type Message struct {
	MessageId   int         `orm:"message_id,primary" json:"message_id"`   // id
	ReceiverId  int         `orm:"receiver_id"        json:"receiver_id"`  // 接收者id
	MessageType int         `orm:"message_type"       json:"message_type"` // 消息类型
	Content     string      `orm:"content"            json:"content"`      // 消息内容
	MessageDes  string      `orm:"message_des"        json:"message_des"`  // 消息描述
	ContentId   int         `orm:"content_id"         json:"content_id"`   // 消息来源id
	CreatedAt   *gtime.Time `orm:"created_at"         json:"created_at"`   // 创建时间
	UpdatedAt   *gtime.Time `orm:"updated_at"         json:"updated_at"`   // 更新时间
	DeletedAt   *gtime.Time `orm:"deleted_at"         json:"deleted_at"`   // 删除时间
}
