// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SignInCourse is the golang structure for table signIn_course.
type SignInCourse struct {
	SignInCourseId int         `orm:"signIn_course_id,primary" json:"signInCourseId"` // id
	Name           string      `orm:"name"                     json:"name"`           // 签到名称，例如2021年2月5日签到
	CourseId       int         `orm:"course_id"                json:"courseId"`       // 课程id
	StuId          int         `orm:"stu_id"                   json:"stuId"`          // 学生id
	CreatedAt      *gtime.Time `orm:"created_at"               json:"createdAt"`      // 创建时间
	UpdatedAt      *gtime.Time `orm:"updated_at"               json:"updatedAt"`      // 更新时间
	DeletedAt      *gtime.Time `orm:"deleted_at"               json:"deletedAt"`      // 删除时间
}
