// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal



// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
    UserRoleId int `orm:"user_role_id" json:"user_role_id"` //           
    UserId     int `orm:"user_id"      json:"user_id"`      // 用户id    
    RoleId     int `orm:"role_id"      json:"role_id"`      // 角色id    
    CreatedAt  int `orm:"created_at"   json:"created_at"`   // 创建时间  
    UpdateAt   int `orm:"update_at"    json:"update_at"`    // 修改时间  
}