// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysApiRole is the golang structure for table sys_api_role.
type SysApiRole struct {
    ApiRoleId int         `orm:"api_role_id,primary" json:"api_role_id"` //           
    RoleId    int         `orm:"role_id"             json:"role_id"`     //           
    ApiId     int         `orm:"api_id"              json:"api_id"`      //           
    CreatedAt *gtime.Time `orm:"created_at"          json:"created_at"`  // 创建时间  
    UpdatedAt *gtime.Time `orm:"updated_at"          json:"updated_at"`  // 修改时间  
}