// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysApi is the golang structure for table sys_api.
type SysApi struct {
    ApiId       int         `orm:"api_id,primary" json:"api_id"`      //           
    Api         string      `orm:"api"            json:"api"`         // api       
    Description int         `orm:"description"    json:"description"` // 描述      
    CreatedAt   *gtime.Time `orm:"created_at"     json:"created_at"`  // 创建时间  
    UpdatedAt   *gtime.Time `orm:"updated_at"     json:"updated_at"`  // 修改时间  
}