// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
    UserId       int         `orm:"user_id,primary" json:"user_id"`      //              
    Email        string      `orm:"email"           json:"email"`        // 邮箱         
    NickName     string      `orm:"nick_name"       json:"nick_name"`    // 昵称         
    RealName     string      `orm:"real_name"       json:"real_name"`    // 真实姓名     
    Password     string      `orm:"password"        json:"password"`     // 姓名         
    Avatar       string      `orm:"avatar"          json:"avatar"`       // 头像         
    Gender       int         `orm:"gender"          json:"gender"`       // 性别         
    Deleted      int         `orm:"deleted"         json:"deleted"`      // 删除标志     
    Major        string      `orm:"major"           json:"major"`        // 专业         
    Organization string      `orm:"organization"    json:"organization"` // 单位         
    UpdateAt     *gtime.Time `orm:"update_at"       json:"update_at"`    // 修改时间     
    CreatedAt    *gtime.Time `orm:"created_at"      json:"created_at"`   // 创建时间     
    Num          string      `orm:"num"             json:"num"`          // 学号/职工号  
}