// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysRole is the golang structure for table sys_role.
type SysRole struct {
    RoleId      int         `orm:"role_id,primary" json:"role_id"`     //           
    Description string      `orm:"description"     json:"description"` // 描述      
    RoleName    string      `orm:"role_name"       json:"role_name"`   // 角色名称  
    CreatedAt   *gtime.Time `orm:"created_at"      json:"created_at"`  // 创建时间  
    UpdateAt    *gtime.Time `orm:"update_at"       json:"update_at"`   // 更新时间  
}