// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	UserId       int         `orm:"user_id,primary"  json:"userId"`       // 主键
	Email        string      `orm:"email,unique"     json:"email"`        // 邮箱
	Num          string      `orm:"num"              json:"num"`          // 学号/职工号
	NickName     string      `orm:"nick_name,unique" json:"nickName"`     // 昵称
	RealName     string      `orm:"real_name"        json:"realName"`     // 真实姓名
	Password     string      `orm:"password"         json:"password"`     // 密码
	Avatar       string      `orm:"avatar"           json:"avatar"`       // 头像
	Gender       int         `orm:"gender"           json:"gender"`       // 性别
	Major        string      `orm:"major"            json:"major"`        // 专业
	Organization string      `orm:"organization"     json:"organization"` // 单位
	UpdatedAt    *gtime.Time `orm:"updated_at"       json:"updatedAt"`    // 修改时间
	CreatedAt    *gtime.Time `orm:"created_at"       json:"createdAt"`    // 创建时间
	DeletedAt    *gtime.Time `orm:"deleted_at"       json:"deletedAt"`    // 删除时间
}
