// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// checkinDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type checkinDetailDao struct {
	*internal.CheckinDetailDao
}

var (
	// CheckinDetail is globally public accessible object for table checkin_detail operations.
	CheckinDetail = &checkinDetailDao{
		internal.CheckinDetail,
	}
)

// Fill with you ideas below.
