// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// courseRecourseDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type courseRecourseDao struct {
	*internal.CourseRecourseDao
}

var (
	// CourseRecourse is globally public accessible object for table course_recourse operations.
	CourseRecourse = &courseRecourseDao{
		internal.CourseRecourse,
	}
)

// Fill with you ideas below.
