// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// courseDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type courseDao struct {
	*internal.CourseDao
}

var (
	// Course is globally public accessible object for table course operations.
	Course = &courseDao{
		internal.Course,
	}
)

// Fill with you ideas below.
