// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// labDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type labDao struct {
	*internal.LabDao
}

var (
	// Lab is globally public accessible object for table lab operations.
	Lab = &labDao{
		internal.Lab,
	}
)

// Fill with you ideas below.
