// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// labSubmitDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type labSubmitDao struct {
	*internal.LabSubmitDao
}

var (
	// LabSubmit is globally public accessible object for table lab_submit operations.
	LabSubmit = &labSubmitDao{
		internal.LabSubmit,
	}
)

// Fill with you ideas below.
