// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// labCommentDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type labCommentDao struct {
	*internal.LabCommentDao
}

var (
	// LabComment is globally public accessible object for table lab_comment operations.
	LabComment = &labCommentDao{
		internal.LabComment,
	}
)

// Fill with you ideas below.
