// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// messageDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type messageDao struct {
	*internal.MessageDao
}

var (
	// Message is globally public accessible object for table message operations.
	Message = &messageDao{
		internal.Message,
	}
)

// Fill with you ideas below.
