// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// signInCourseDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type signInCourseDao struct {
	*internal.SignInCourseDao
}

var (
	// SignInCourse is globally public accessible object for table signIn_course operations.
	SignInCourse = &signInCourseDao{
		internal.SignInCourse,
	}
)

// Fill with you ideas below.
