// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// sysApiRoleDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysApiRoleDao struct {
	*internal.SysApiRoleDao
}

var (
	// SysApiRole is globally public accessible object for table sys_api_role operations.
	SysApiRole = &sysApiRoleDao{
		internal.SysApiRole,
	}
)

// Fill with you ideas below.