// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"time"
)

// sysUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserDao struct {
	*internal.SysUserDao
}

var (
	// SysUser is globally public accessible object for table sys_user operations.
	SysUser = &sysUserDao{
		internal.SysUser,
	}
)

// Fill with you ideas below.

func (s *sysUserDao) GetRoleById(userId int) (int, error) {
	role, err := g.Table("sys_user").InnerJoin("sys_user_role").
		Where("sys_user.user_id =", userId).And("sys_user.user_id = sys_user_role.user_id").Cache(time.Hour).
		FindValue("sys_user_role.role_id")
	if err != nil {
		return 0, err
	}
	return role.Int(), nil
}

func (s *sysUserDao) ListUserIdByRole(roleId int) ([]gdb.Value, error) {
	userId, err := g.Table("sys_user_role").Where("role_id =", roleId).FindArray("user_id")
	if err != nil {
		return nil, err
	}
	return userId, err
}
