// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"code-platform/app/dao/internal"
)

// sysApiDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysApiDao struct {
	*internal.SysApiDao
}

var (
	// SysApi is globally public accessible object for table sys_api operations.
	SysApi = &sysApiDao{
		internal.SysApi,
	}
)

// Fill with you ideas below.